#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define MAXLEN 100
#define LINELEN 80
#define EXTRACHARS 2

#define REQ_ARGS 2
#define NUM_ARGS 1

#define ITINERATOR 1

typedef enum {
    FALSE,
    TRUE
} BOOLEAN;

BOOLEAN loop = FALSE;

FILE *open_file(const char *fname) {
    FILE *reader;
    reader = fopen(fname, "r");
    if (!reader) {
        perror("fopen");
    }
    return reader;
}

char display(FILE *reader) {
    char c;
    c = fgetc(reader);
    while (c != EOF) {
        printf("%c", c);
        c = fgetc(reader);
    }
    return c;
}

/*static as the function does not need to be accessed outside*/
static void read_rest_of_line(FILE *reader) {
    int ch;
    while (ch = getchar(), ch != EOF && ch != '\n')
        ;
    clearerr(reader);
}

char lineWrite(FILE *reader, char *name) {
    char c[LINELEN + EXTRACHARS];
    char e;
    int b;
    b = 0;

    while (fgets(c, LINELEN + EXTRACHARS, reader)) {
        /*buffer overflow test and management*/
        if (c[strlen(c) - 1] != '\n') {
            /*error generated by program, not system
            so custom error message is necessary*/
            printf("Error, buffer overflow! \n");
            read_rest_of_line(reader);
            continue;
        }
        /*remove trailing newline*/
        c[strlen(c) - 1] = 0;

        /*counter for line*/
        b += 1;
        /*print out requirements*/
        printf("%s line %d %s\n", name, b, c);

        /*puts(c);*/

        loop = TRUE;
    }

    if (loop != FALSE) {
        e = 1;
    }

    return e;
}

int main(int argc, char *argv[]) {
    /*char fname[MAXLEN + EXTRACHARS];*/
    int c;
    FILE *reader;
    char d;
    char name[MAXLEN];

    for (c = ITINERATOR; c < argc; ++c) {
        /*compare strings to detect the presence of -n
        strcmp will return 0 if so*/
        if (strcmp("-n", argv[1]) == 0) {
            /*open the file*/
            if (argv[c + 1] != NULL) {
                printf("Entitled: %s\n", argv[c + 1]);
                reader = open_file(argv[c + 1]);
                /*if the file could not be opened, pass an error to let the user
                 * know*/
                if (!reader) {
                    return EXIT_FAILURE;
                }
                strcpy(name, argv[c + 1]);
                puts(name);
                /*print function-this one uses fgets*/
                d = lineWrite(reader, name);
                /*if file could not be processed and printed, pass an error to
                 * let the user know*/
                if (!d) {
                    fprintf(stderr,
                            "Error: the file has not been passed from main to "
                            "the function \n");
                }
                /*close the file*/
                fclose(reader);
            }
        } else if (strcmp("-n", argv[1]) != 0) {

            /*open the file*/

            reader = open_file(argv[c]);
            /*if the file could not be opened, pass an error to let the user
             * know*/
            if (!reader) {
                return EXIT_FAILURE;
            } else {
                /*print function-this one uses fgetc*/
                d = display(reader);
                /*if file could not be processed and printed, pass an error to
                 * let the user know*/
                if (!d) {
                    fprintf(stderr,
                            "Error: the file has not been passed from main to "
                            "the function \n");
                }
            }
            /*close the file*/
            fclose(reader);
        } else {
            fprintf(stderr, "Sorry not all the files can be opened");
        }
    }

    return EXIT_SUCCESS;
}
